lab1
frontend-tinkoff-ekb/rtf-lab-1 pull request #101
Opened 2019-10-14 16:52 UTC by Kourov-Kirill

solution

2019-10-14 17:18 UTC, Kourov-Kirill commented
У меня не было возможности делать лабораторную работу на своем компьютере. Поэтому делал на компьютере одногруппника, что вы можете заметить. Простите, пожалуйста.

2019-10-15 11:18 UTC, AlexNg9 commented
> У меня не было возможности делать лабораторную работу на своем компьютере. Поэтому делал на компьютере одногруппника, что вы можете заметить. Простите, пожалуйста.

Почему работа сделана не из под вашей учетной записи? Общий компьютер – ок, но учетные записи вы должны менять.

2019-10-15 15:48 UTC, Kourov-Kirill commented
Я работал в GitHub Desktop, с чужого аккаунта вышел, зашел на свой, но сам не понял почему остался его

2019-10-16 09:29 UTC, ghost requested changes

2019-10-16 09:29 UTC, AlexNg9 commented on index.js
> +    for (let i = 0; i < array.length; i++) {
Посмотрите, какие у массива есть методы для проверки элементов.

2019-10-16 09:29 UTC, AlexNg9 commented on index.js
> +    let summ = Number(string);
Можно в этой же строке прибавить число и объявить через const.

2019-10-16 09:29 UTC, AlexNg9 commented on index.js
> +    return result.map(Number);
Почему переменная называется результат, если в итоге возвращаем что-то другое?

2019-10-22 06:28 UTC, closed without merging