FirstLabVasillev.js
frontend-tinkoff-ekb/rtf-lab-1 pull request #104
Opened 2019-10-14 17:58 UTC by evg100eny

2019-10-15 11:48 UTC, ghost requested changes

2019-10-15 11:48 UTC, AlexNg9 commented on index.js
> +    if (!array.every((item) => (typeof item) === 'number')) { return null; }
На отдельную строку return.

2019-10-15 11:48 UTC, AlexNg9 commented on index.js
> +    if (!array.every((item) => (typeof item) === 'number')) { return null; }
(typeof item) – скобки лишние.

2019-10-15 11:48 UTC, AlexNg9 commented on index.js
> +    for (let i = 0; i < arrayOfString.length; i++) {
Используйте map.

2019-10-20 17:56 UTC, evg100eny commented
Исправил замечания.

2019-10-21 06:31 UTC, ghost approved these changes
👍

2019-10-21 06:31 UTC, AlexNg9 commented on index.js
> +    return (arrayOfNumbers);
Скобки лишние.

2019-10-21 06:31 UTC, closed without merging