Lab1
frontend-tinkoff-ekb/rtf-lab-1 pull request #13
Opened 2019-10-09 18:10 UTC by Maxerdan

2019-10-10 07:09 UTC, ghost requested changes

2019-10-10 07:09 UTC, AlexNg9 commented on index.js
> +    if(typeof(number) == 'number' && number === Math.trunc(number) && number >= 0) {
Условием задачи гарантируется, что на вход придет положительное натуральное число или 0.

2019-10-10 07:09 UTC, AlexNg9 commented on index.js
> +        }
`} else {`

2019-10-10 07:09 UTC, AlexNg9 commented on index.js
> +        if(typeof(array[i]) === 'number' && array[i] === Math.trunc(array[i]) && array[i] >= 0 && array[i] <= 9) {
Пробел после if/for.

2019-10-10 07:09 UTC, AlexNg9 commented on index.js
> +    for(let i = 0; i < array.length; i++) {
Можно разделить валидацию массива и получение строки из его чисел. Также стоит использовать методы массива, которые для этого подходят.

2019-10-10 11:31 UTC, ghost requested changes

2019-10-10 11:31 UTC, ghost commented on index.js
> +    {
{ на предыдущую строку

2019-10-10 11:31 UTC, ghost commented on index.js
> +        array.every(item => stringOfNumbers += item);
Этот метод служит для проверки, что каждый элемент массива удовлетворяет заданному условию, он возвращает boolean. В данной ситуации его использование неуместно.

2019-10-10 11:58 UTC, Maxerdan commented
Не совсем понимаю, чем плох цикл и зачем нужно "разделить валидацию массива и получение строки из его чисел"

2019-10-10 14:36 UTC, ghost commented
> Не совсем понимаю, чем плох цикл и зачем нужно "разделить валидацию массива и получение строки из его чисел"

Использование every в условии было правильным. Его нужно вернуть.
Но внутри if оно было не уместно, так как метод служит для другого.
Цикл не плох, но у массива есть специальные методы, которые лучше подходят для такого рода задач и выглядят синтаксически понятнее.

2019-10-10 16:05 UTC, Maxerdan commented
Заменил цикл for на метод для массива, а в условии изменил на some, чтобы проверяла не все, а при обнаружении хоть единственного неправильного элемента массива тут же выкидывала null

2019-10-11 07:27 UTC, ghost requested changes

2019-10-11 07:27 UTC, AlexNg9 commented on index.js
> +    if (array.some(item => ((typeof(item) != 'number') || (item != Math.trunc(item)) || (item < 0) || (item > 9)))) {
Строгое неравенство. !==
Слишком много лишних скобок в функции. Можно убрать все, кроме typeof(item) и Math.trunc(item).

2019-10-11 07:27 UTC, AlexNg9 commented on index.js
> +        array.every(item => stringOfNumbers += item);
Еще раз повторяю: не надо использовать этот метод для конкатенации строк. Да, этот метод проходит по всем элементам, но его использование здесь неуместно. Таким образом можно использовать тогда любой другой метод массива: some/map и тд. Но они все для этого не подходят. Они имеют другой смысл.
Если хочется в какую-то внешнюю переменную собрать какой-то результат, можно использовать forEach. Либо в данном случае еще лучше использовать reduce – тогда не придется отдельной строкой объявлять переменную, а стартовое значение можно будет передать прямо в метод reduce.

2019-10-11 07:27 UTC, ghost commented on index.js
> +    if (array.some(item => ((typeof(item) != 'number') || (item != Math.trunc(item)) || (item < 0) || (item > 9)))) {
Пустые строки вокруг if/for, перед return.

2019-10-13 07:03 UTC, Maxerdan commented
Использовал reduce, но передать в него число не получилось, либо этот метод складывал как строки, либо как числа, такого чтобы он сложил сначала как строки элементы массива, а потом прибавил как к числу другое число не получилось

2019-10-13 14:31 UTC, ghost requested changes

2019-10-13 14:31 UTC, AlexNg9 commented on index.js
> +    StringOfNumbers += parseInt(array.reduce((total, current) => total + current.toString()), 10);
В reduce надо передать пустую строку в качестве аккумулятора.

2019-10-13 14:31 UTC, AlexNg9 commented on index.js
> +    let StringOfNumbers = number;
Строка чисел, но присваиваем число.

2019-10-13 14:31 UTC, AlexNg9 commented on index.js
> +    let StringOfNumbers = number;
В нижнем регистре первая буква переменной.

2019-10-13 15:09 UTC, ghost approved these changes

2019-10-13 15:09 UTC, AlexNg9 commented on index.js
> +    numbers = number + parseInt(array.reduce((current) => numbers + current.toString()), 10);
Аккумулятор в reduce передается аргументом. не нужно отдельно объявлять переменную.
`array.reduce(() => {...}, acc)`

2019-10-13 15:11 UTC, AlexNg9 commented
Тесты упали

2019-10-13 15:21 UTC, Maxerdan commented
Увидел, сейчас исправлю

2019-10-14 05:53 UTC, ghost approved these changes

2019-10-14 05:53 UTC, AlexNg9 commented on index.js
> +    if (array.some((item) => typeof (item) !== 'number' || item !== Math.trunc(item) || item < 0 || item > 9)) {
Скобки лишние вокруг item

2019-10-14 05:53 UTC, AlexNg9 commented on index.js
> +    let sumString = parseInt(array.reduce((total, current) => total + current.toString(), ''), 10);
reduce внутри parseInt выглядит громоздко.
Лучше бы в отдельную переменную результат сложить.

2019-10-14 05:53 UTC, AlexNg9 commented
👍

2019-10-14 05:53 UTC, closed without merging