Create dz_lab_1_hope_is_correct
frontend-tinkoff-ekb/rtf-lab-1 pull request #16
Opened 2019-10-10 11:47 UTC by VladimirSTAR0911

2019-10-10 16:02 UTC, M1M0G commented
Вован, зачем ты проверяешь каждый элемент отдельно?(NO TOXIC)

2019-10-10 18:15 UTC, DesperateHiking commented
тож выпал, если такое на хакатоне провернуть можно стать мемом (посмертно)

2019-10-11 12:25 UTC, AlexNg9 commented
Ребят, зачем вы лезете в чужие PR'ы? @M1M0G @DesperateHiking

2019-10-14 14:27 UTC, AlexNg9 commented on index.js
> +// Это пиздец какой-то
Первое и последнее предупреждение. В следующий раз – закрою задачу.

2019-10-14 15:31 UTC, VladimirSTAR0911 commented on index.js
> +// Это пиздец какой-то
Понял и принял. Такого больше не повторится.

2019-10-15 10:06 UTC, ghost requested changes

2019-10-15 10:06 UTC, AlexNg9 commented on index.js
> +            outNums = 'exit';
Как минимум, такие переменные обычно имеют тип boolean (флаг).
И это переменная избыточна, так как ниже сразу идет return null, поэтому не возникнет ситуации, что на последней строке `outNums === 'exit'`.

2019-10-15 10:06 UTC, AlexNg9 commented on index.js
> +    return outNums === 'exit' ? null : Array.from(String(Number(outNums) + number)).map((arr) => Number(arr));
Лучше разбить цепочку вызовов. Хотя бы что-то выделить в переменную, строку от чисел, например.
arr – непонятный аргумент. Обычно так называют массивы, а не его элементы.

2019-10-15 10:06 UTC, AlexNg9 commented on index.js
> +    if (typeof array !== 'object' && typeof number !== 'number') return null;
Лучше на отдельную строку return для читаемости.

2019-10-16 09:12 UTC, VladimirSTAR0911 commented on index.js
> +    return outNums === 'exit' ? null : Array.from(String(Number(outNums) + number)).map((arr) => Number(arr));
Объявление переменных(когда этого можно избежать) не будет лишним в коде?
    В плане загрузки памяти, эффективности, скорости и т.д.
    Понятно что в этой маленькой проге это ни на что не повлияет, но просто в общем интересно.

2019-10-16 09:49 UTC, AlexNg9 commented on index.js
> +    return outNums === 'exit' ? null : Array.from(String(Number(outNums) + number)).map((arr) => Number(arr));
На скорость это никак не влияет. На память тоже. Область памяти в любом случае выделяется, чтобы сохранить временное значение. Другой вопрос сложите ли вы его в переменную (дадите этой области памяти имя) или нет. Нужные массивы/строки/числа в любом случае создаются, пусть и на лету.

2019-10-16 09:51 UTC, ghost requested changes

2019-10-16 09:51 UTC, AlexNg9 commented on index.js
> +    outArray = outArray.map((el) => Number(el));
Тут можно было сразу вернуть.

2019-10-16 09:51 UTC, AlexNg9 commented on index.js
> +    outArray = Array.from(String(Number(outNums) + number));
Переменную можно было объявить здесь.

2019-10-16 09:51 UTC, AlexNg9 commented on index.js
> +        if ((array[i] < 0 || array[i] > 9) || typeof array[i] !== 'number') {
Сделайте валидацию массива отдельно. Используйте методы массива.

2019-10-16 09:51 UTC, AlexNg9 commented on index.js
> +        outNums += array[i];
Посмотрите на reduce или join.

2019-10-16 17:30 UTC, VladimirSTAR0911 commented on index.js
> +        if ((array[i] < 0 || array[i] > 9) || typeof array[i] !== 'number') {
Я использовал методы массива, но это не устраивало тестировщик. Поэтому изменил на банальный цикл.

2019-10-16 17:31 UTC, VladimirSTAR0911 commented on index.js
> +    outArray = outArray.map((el) => Number(el));
не получалось вернуть сразу. Не знаю почему. Так вернуть получилось корректно.

2019-10-16 17:31 UTC, VladimirSTAR0911 commented on index.js
> +    outArray = Array.from(String(Number(outNums) + number));
Объявлял, тестировщик ругался.

2019-10-17 06:34 UTC, AlexNg9 commented on index.js
> +    outArray = outArray.map((el) => Number(el));
Надо смотреть на конкретные ошибки и их исправлять. Попробуйте еще раз. Поищите в Гугле, как устранить ошибку. Если будет все равно не понятно, спрашивайте.

2019-10-17 06:34 UTC, AlexNg9 commented on index.js
> +    outArray = Array.from(String(Number(outNums) + number));
Как объявляли?

2019-10-17 06:35 UTC, AlexNg9 commented on index.js
> +        if ((array[i] < 0 || array[i] > 9) || typeof array[i] !== 'number') {
Как использовали? Аналогично – давайте смотреть и обсуждать. Заливайте вариант, который не проходит тесты.

2019-10-20 15:04 UTC, AlexNg9 commented
@VladimirSTAR0911 жду правок или вопросов.

2019-10-22 06:30 UTC, ghost approved these changes
👍

2019-10-22 06:30 UTC, AlexNg9 commented on index.js
> +    outNums = array.reduce((sum, item) => sum + item, '');
Можно было на предыдущей строке сразу присвоить и через const.

2019-10-22 06:30 UTC, AlexNg9 commented on index.js
> +        || !array.every((item) => Number.isInteger(item) || (item < 0 && item > 9))) {
Перегруженное условие – цикл лучше вынести в переменную.

2019-10-22 06:30 UTC, closed without merging