FirstLesson
frontend-tinkoff-ekb/rtf-lab-1 pull request #19
Opened 2019-10-10 14:55 UTC by Komodood

Round ONE

2019-10-13 11:56 UTC, Komodood commented
Не писал коммиты, потому что скорее пытался за пушить
Итог: Некоторые мои проверки либо проверяют одно и то же, либо с ними не работает проверка тестов.
Ошибка в половине случаев всех моих версий этой проги: неправильный вывод результата(выдавало например: [13] вместо [1, 3])
Начальные ошибки: из данного массива не записывалось число в переменную. Постоянно выдавало undefined.
Пробовал вариант с математическим добавлением в массив(число % 10 и добавление в число)
Такой вариант пропал в бездне всех вариаций.
В какой то момент начал отладчиком проходить в MVC и пробовать разные варианты данных.

2019-10-13 14:25 UTC, AlexNg9 commented
> Не писал коммиты, потому что скорее пытался за пушить

Куда торопились? Лучше писать нормальные сообщения коммитов.

2019-10-13 14:28 UTC, ghost requested changes

2019-10-13 14:28 UTC, AlexNg9 commented on index.js
> +    let NewNum = 0;
Первая буква должна быть в нижнем регистре.

2019-10-13 14:28 UTC, AlexNg9 commented on index.js
> +    if (array.some((item) => item === null || item > 9 || item < 0 || Math.trunc(item) !== item || typeof (item) !== 'number' || Number.isInteger(item) === false)) return null;// Проверка на подходящ
`Number.isInteger()` – убирает необходимость в проверках на null и тип элемента.

2019-10-13 14:28 UTC, AlexNg9 commented on index.js
> +    if (array.some((item) => item === null || item > 9 || item < 0 || Math.trunc(item) !== item || typeof (item) !== 'number' || Number.isInteger(item) === false)) return null;// Проверка на подходящ
Сам метод в явно виде возвращает boolean. Поэтому не нужно его приравнивать к true/false.
Нужно брать результат метода или его отрицание. (!Number.isInteger()).

2019-10-13 14:28 UTC, AlexNg9 commented on index.js
> +    NewMass = NewNum.toString(10).split('').map(Number);
Можно сразу результат вернуть, без перезаписи переменной.

2019-10-14 11:09 UTC, Komodood commented
Закончил исправлять, жду проверки

2019-10-14 14:13 UTC, ghost approved these changes
👍

2019-10-14 14:13 UTC, AlexNg9 commented on index.js
> +    newNum = parseInt(array.join(''), 10);
Можно объявить переменную прямо здесь.

2019-10-14 14:13 UTC, AlexNg9 commented on index.js
> +    || !Number.isInteger(item))) return null;
Форматирование поплыло. Лучше return на отдельную строку.

2019-10-14 14:13 UTC, closed without merging