lesson-01
frontend-tinkoff-ekb/rtf-lab-1 pull request #21
Opened 2019-10-10 16:16 UTC by AndrewMarshal

2019-10-11 07:55 UTC, frontend-tinkoff-ekb commented
Найди 10 отличий https://github.com/frontend-tinkoff-ekb/rtf-lab-1/pull/8/files

2019-10-11 08:01 UTC, AndrewMarshal commented
> Найди 10 отличий https://github.com/frontend-tinkoff-ekb/rtf-lab-1/pull/8/files

2019-10-11 08:02 UTC, AndrewMarshal commented
Лол, похож

2019-10-11 08:06 UTC, AndrewMarshal commented
Я делал по лекции вашей задание (слайд 37, я из него брал материал там даже синтаксис такой же как в 1-м моем варианте)

2019-10-11 08:11 UTC, AlexNg9 commented
> Я делал по лекции вашей задание (слайд 37, я из него брал материал там даже синтаксис такой же как в 1-м моем варианте)

На 37 слайде я вижу последнюю строку вашего решения, хорошо. А все остальное до этого?

2019-10-11 08:20 UTC, AndrewMarshal commented
Про то как работает let - Вы на лекции рассказывали, первое условие в if (проверка на дробное число) - мне одногруппник вчера подсказал, а остальное - из условия задания написаны

2019-10-11 08:26 UTC, AndrewMarshal commented
И totalAmount я написал не как var, а как const - потому что оно не должно меняться, когда выдает ответ. Дополнительно брал я информацию вот здесь: https://learn.javascript.ru/let-const

2019-10-11 08:28 UTC, frontend-tinkoff-ekb commented on index.js
> +    for (let i = 0; i < array.length; i++) {
Переделать с for на более подходящий цикл

2019-10-11 08:28 UTC, frontend-tinkoff-ekb commented on index.js
> +    const totalAmount  = number + parseInt(numStr);
Зачем переменная создана в конце файла?

2019-10-11 08:28 UTC, frontend-tinkoff-ekb commented on index.js
> +    numStr  = totalAmount .toString(10);
Что за пробел?

2019-10-11 08:28 UTC, frontend-tinkoff-ekb commented on index.js
> - * @param number – число, которое нужно прибавить к числу, полученному из массива
Зачем JSDOC убил?

2019-10-11 08:28 UTC, frontend-tinkoff-ekb commented on index.js
> +function addNumber( array, number)
Что за пробел перед array?

2019-10-11 15:02 UTC, AndrewMarshal commented
Поменял цикл, поправил отступы и убрал лишние пробелы

2019-10-13 09:53 UTC, AndrewMarshal commented
Заменил цикл while на forEach, но тут у меня пошли ошибки, из-за которых я в недоумении:  
1) местами просит перенести return на новую и ожидает пустую строку перед этим, но когда это делаешь - мне пишет, что так делать нельзя (что я, естественно, понимаю, что так делать нельзя), вернул все обратно;
2) местами тоже просит перенести скобочки, например, if (...) {   - вот это правильный синтаксис, но он просит перенести после if, а когда переношу, то пишет, что ожидается скобочка в строке с if.... ;
3) выдавало ошибку "Expected linebreaks to be 'LF' but found 'CRLF'" - я ее поправил, но раньше такого не было, не знаю почему ее начало выдавать;
4) тест рушится из-за module.exports: он просит поставить там зачем-то запятую, но ее там не надо же ставить;
5) еще в ошибках выдавало поставить в parseInt параметр 'radix', - поставил, но до этого не выдавало мне данную ошибку и еще прочитал, что это необязательный параметр, по идее.

2019-10-13 17:06 UTC, AndrewMarshal commented
Ураааааа!!!!!!

2019-10-13 17:07 UTC, AndrewMarshal commented
Поменял цикл while на forEach, долго не мог понять, почему у меня не проходило 2 теста, в итоге понял, что forEach не возвращает исключение с null...

2019-10-15 06:33 UTC, ghost requested changes

2019-10-15 06:33 UTC, AlexNg9 commented on index.js
> +    array.forEach((_item, i) => {
Используйте reduce.

2019-10-15 06:33 UTC, AlexNg9 commented on index.js
> +    if (!(array.every((item) => item === Math.ceil(item) && item >= 0 && item <= 9 && (typeof (item) === 'number') && (typeof (number) === 'number')))) {
Зачем каждый раз проверять тип переменной number?
Лучше выделить цикл в переменную для читаемости.

2019-10-15 06:33 UTC, AlexNg9 commented on index.js
> +    return (number + parseInt(numLine, 10)).toString(10).split('').map((item) => parseInt(item, 10));
Число лучше вынести в переменную, очень громоздкая запись получается.

2019-10-15 06:34 UTC, AlexNg9 commented
> Поменял цикл while на forEach, долго не мог понять, почему у меня не проходило 2 теста, в итоге понял, что forEach не возвращает исключение с null...

forEach пробегает по элементам, но никакого результата не возвращает, да.

2019-10-17 15:37 UTC, AndrewMarshal commented
Сделал вместо forEach функцию reduce и поправил остальные замечания

2019-10-18 06:43 UTC, ghost approved these changes
За задачу половину баллов за списывание. Можете попробовать оспорить в субботу.

2019-10-18 06:43 UTC, AlexNg9 commented on index.js
> +    numLine = array.reduce((accumulator, item) => accumulator + item, numLine);
Можно было здесь переменную объявить.

2019-10-18 06:43 UTC, AlexNg9 commented on index.js
> +    totalAmount = number + parseInt(numLine, 10);
Аналогично здесь объявить через const.

2019-10-18 06:44 UTC, closed without merging