task1
frontend-tinkoff-ekb/rtf-lab-1 pull request #22
Opened 2019-10-10 17:30 UTC by Nordennavic

2019-10-11 07:57 UTC, ghost requested changes

2019-10-11 07:57 UTC, AlexNg9 commented on package.json
> +    "mocha": "^6.2.1"
Зачем? Что не так с jest? Эти файлы не должны меняться

2019-10-11 07:57 UTC, AlexNg9 commented on index.js
> +        if(typeof(i) === 'number' && !isNaN(i)) result += i;
```
if (...) {
...
} else {
...
}
```

2019-10-11 07:57 UTC, AlexNg9 commented on index.js
> +        result[i] = parseInt(result[i]);
Почему здесь parseInt, а выше через +?

2019-10-11 07:57 UTC, AlexNg9 commented on index.js
> +    result = result.split('');
Не стоит в переменную перезаписывать разные типы значений.

2019-10-11 07:57 UTC, AlexNg9 commented on index.js
> +    for(let i = 0; i < result.length; i++)
Посмотрите на метод map.

2019-10-11 19:00 UTC, Nordennavic commented
Стилистически изменил if, унифицировал парсинг в инт, применил map, добавил больше новых переменных.

2019-10-11 19:02 UTC, Nordennavic commented on index.js
> +        if(typeof(i) === 'number' && !isNaN(i)) result += i;
В js принято даже однострочные действия после if'ов переносить в отдельную строчку?

2019-10-11 19:04 UTC, Nordennavic commented on package.json
> +    "mocha": "^6.2.1"
Прошу прощения, это вышло случайно. Я изначально работал в атоме и тесты ну вообще никак не запускались, поэтому я пробовал разные библиотеки (в итоге просто перешёл в webstorm и всё спокойно само установилось и запустилось).

2019-10-14 10:38 UTC, AlexNg9 commented
Пробуйте сейчас.

2019-10-14 11:42 UTC, Nordennavic commented
Что пробовать?

2019-10-14 11:46 UTC, Nordennavic commented
Вы мне уже зачли другую ветку (lesson-1, там ещё мем лежит). Я создал пр из другой ветки, потому что здесь были изменены файлы, которые вы сказали не трогать (из-за того, что атом не хотел тесты запускать).

2019-10-14 14:34 UTC, closed without merging

2019-10-14 14:37 UTC, AlexNg9 commented on index.js
> +        if(typeof(i) === 'number' && !isNaN(i)) result += i;
@Nordennavic

> В js принято даже однострочные действия после if'ов переносить в отдельную строчку?

Да не только в js. Когда в одну строку, условие сливается с действием – хуже читаемость.