Add files via upload
frontend-tinkoff-ekb/rtf-lab-1 pull request #28
Opened 2019-10-11 13:47 UTC by LuckyLiar

normalno?

2019-10-13 09:29 UTC, LuckyLiar commented
ура, прошлось

2019-10-13 14:17 UTC, ghost requested changes

2019-10-13 14:17 UTC, AlexNg9 commented on index.js
> +    const array1 = [];
array1 – название переменной не несет никакого смысла.

2019-10-13 14:17 UTC, AlexNg9 commented on index.js
> +    let transnum = '';
Аналогично из названия непонятно, что здесь хранится.

2019-10-13 14:17 UTC, AlexNg9 commented on index.js
> +    transnum = (+transnum + number).toString(10);
Лучше использовать другие способы приведения строки к числу.

2019-10-13 14:17 UTC, AlexNg9 commented on index.js
> +addNumber([1, 0, 9], 2); // 109 + 2 = 111; => [1, 1, 1]
Лишнее.

2019-10-13 14:17 UTC, AlexNg9 commented on index.js
> +        if (typeof (array[i]) === 'number' && array[i] >= 0 && array[i] <= 9 && array[i] === Math.trunc(array[i])) {
Разделите валидацию массива и получение числа из массива.

2019-10-13 14:45 UTC, LuckyLiar commented on index.js
> +        if (typeof (array[i]) === 'number' && array[i] >= 0 && array[i] <= 9 && array[i] === Math.trunc(array[i])) {
имеется в виду выделить условие в отдельную переменную?

2019-10-13 14:51 UTC, AlexNg9 commented on index.js
> +        if (typeof (array[i]) === 'number' && array[i] >= 0 && array[i] <= 9 && array[i] === Math.trunc(array[i])) {
Нет, можно использовать удобный метод массива, который специально для этого нужен. Тогда будет два цикла последовательных.

2019-10-13 15:57 UTC, LuckyLiar commented
fixed

2019-10-14 10:40 UTC, ghost requested changes

2019-10-14 10:40 UTC, AlexNg9 commented on index.js
> +    let translatedNum = '';
Все равно как-то не очень. translated – переведенное? Куда, во что?

2019-10-14 10:40 UTC, AlexNg9 commented on index.js
> +    const finalArr = [];
Лучше объявлять ближе к месту первого использования.

2019-10-14 10:40 UTC, AlexNg9 commented on index.js
> +        if (!(typeof (array[i]) === 'number' && array[i] >= 0 && array[i] <= 9 && array[i] === Math.trunc(array[i]))) {
Используйте метод массива для такой проверки. Посмотрите, какой подходит.

2019-10-14 10:40 UTC, AlexNg9 commented on index.js
> +    const translatedArr = array.reduce((result, item) => result + item.toString());
В reduce лучше передавать стартовое значение.

2019-10-14 10:40 UTC, AlexNg9 commented on index.js
> +    for (let i = 0; i < translatedNum.length; i++) {
Напоминаю про map.

2019-10-14 14:32 UTC, LuckyLiar commented
оптимизировал максимально(надеюсь)

2019-10-15 10:01 UTC, ghost requested changes

2019-10-15 10:01 UTC, ghost commented on index.js
> +    const isFromZeroToNine = array.every((item) => item >= 0) && array.every((item) => item < 10);
Зачем 2 раза бегать по массиву?

2019-10-15 10:01 UTC, AlexNg9 commented on index.js
> +    if (!(array.every((item) => Number.isInteger(item))) || !(isFromZeroToNine)) {
Еще есть метод some. Можно взять отрицание текущего условия для every – если какой-то из элементов невалиден, возвращаем null.
И можно будет убрать отрицание перед every.
Исправлять не обязательно, просто чтоб знали.

2019-10-15 10:01 UTC, AlexNg9 commented on index.js
> +    const finalArr = summedNum.split('').map((item) => parseInt(item, 10));
Можно сразу вернуть.

2019-10-15 10:01 UTC, AlexNg9 commented on index.js
> +    const translatedArr = array.reduce((result, item) => result + item.toString(), 0);
Все равно не понятно. Переведенный во что? numberFromArray хотя бы, например.

2019-10-15 13:31 UTC, LuckyLiar commented
есть

2019-10-16 09:25 UTC, ghost approved these changes

2019-10-16 09:25 UTC, AlexNg9 commented on index.js
> +    if (!(array.every((item) => Number.isInteger(item))) || !(isFromZeroToNine)) {
!(isFromZeroToNine) – скобки лишние. Вокруг every тоже.

2019-10-16 09:25 UTC, AlexNg9 commented on index.js
> +    const numberFromArray = array.reduce((result, item) => result + item.toString(), 0);
Хотите получить строку. Тогда стартовым значением аккумулятора должно быть '' – пустая строка.

2019-10-16 09:25 UTC, AlexNg9 commented
👍

2019-10-16 09:25 UTC, closed without merging