Laba1
frontend-tinkoff-ekb/rtf-lab-1 pull request #29
Opened 2019-10-11 13:50 UTC by needMoreBlood

Лаба №1

2019-10-14 07:17 UTC, ghost requested changes

2019-10-14 07:17 UTC, AlexNg9 commented on index.js
> +    for (let i = 0; i < array.length; i++) {
У массива есть метод, который проверяет условие на всех его элементах.

2019-10-14 07:17 UTC, AlexNg9 commented on index.js
> +    for (let i = 0; i < array.length; i++) {
Попробуйте через reduce.

2019-10-14 07:17 UTC, AlexNg9 commented on index.js
> +    let number1 = parseInt(num, 10);
Плохое название для переменной. Можно сразу же здесь number прибавить.

2019-10-14 07:17 UTC, AlexNg9 commented on index.js
> +    if (number1 === 0) arr[0] = 0;
Можно сразу и вернуть массив здесь тогда.

2019-10-14 07:17 UTC, AlexNg9 commented on index.js
> +    while (number1 > 0) {
Тоже можно через reduce.

2019-10-15 06:06 UTC, needMoreBlood commented
1. использовала some для проверки элементов массива
2. применила reduce для записи в число из массива
3.  изменила название 
4. при проверки сразу вернула массив
но не смогла заменить while на reduce. буду еще пытаться, но пока что только так

2019-10-15 07:22 UTC, ghost requested changes

2019-10-15 07:22 UTC, AlexNg9 commented on index.js
> +    const arr = [];
Переменную объявить ниже можно.

2019-10-15 07:22 UTC, AlexNg9 commented on index.js
> +        return arr;
А здесь return [0];

2019-10-15 07:22 UTC, AlexNg9 commented on index.js
> +    if (array.length < 1) return null;
return на следующую строку. Сейчас читаемость хуже

2019-10-15 07:22 UTC, AlexNg9 commented on index.js
> +    num = array.reduce((accumulator, item) => accumulator + item, '');
Можно переменную здесь объявить.

2019-10-15 07:22 UTC, AlexNg9 commented on index.js
> +    while (newNumber > 0) {
Забудем про reduce. Я ошибся.

2019-10-15 18:19 UTC, needMoreBlood commented
1. переменную newNumber объявила ниже
2. если новое число равно 0, сразу вернула  return [0]
3. при проверки перенесла return на строку ниже
4. переменную num объявила ниже, сразу при присвоении ей значения

2019-10-16 08:56 UTC, ghost approved these changes
👍

2019-10-16 08:56 UTC, AlexNg9 commented on index.js
> +    if (array.some((item) => typeof (item) !== 'number' || item > 9 || item < 0)) return null;
Лучше переносить на следующую строку return. Сейчас читаемость хуже, сливается действие с условием.

2019-10-16 08:56 UTC, AlexNg9 commented on index.js
> +    if (array.some((item) => typeof (item) !== 'number' || item > 9 || item < 0)) return null;
Можно выделить some в переменную и в одном if сразу проверить длину массива (выше) и валидацию массива, чтобы не писать несколько условий.

2019-10-16 08:57 UTC, closed without merging