Сделал лабораторную работу
frontend-tinkoff-ekb/rtf-lab-1 pull request #30
Opened 2019-10-11 15:24 UTC by nekitlnp

2019-10-12 18:41 UTC, frontend-tinkoff-ekb commented
1:4   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
   2:55  error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
   3:81  error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
   4:3   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
   5:10  error  'addNumber' is defined but never used                                                                                                                                  no-unused-vars
   5:36  error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
   6:8   error  There should be no spaces inside this paren                                                                                                                            space-in-parens
   6:21  error  'isSomeArrayValueNaN' was used before it was defined                                                                                                                   no-use-before-define
   6:42  error  There should be no spaces inside this paren                                                                                                                            space-in-parens
   6:45  error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
   7:1   error  Expected indentation of 8 spaces but found 4                                                                                                                           indent
   7:17  error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
   8:6   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
   9:1   error  Trailing spaces not allowed                                                                                                                                            no-trailing-spaces
   9:5   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
  10:8   error  There should be no spaces inside this paren                                                                                                                            space-in-parens
  10:11  error  'isNumberPositiveAndInteger' was used before it was defined                                                                                                            no-use-before-define
  10:46  error  There should be no spaces inside this paren                                                                                                                            space-in-parens
  10:49  error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
  11:1   error  Expected indentation of 8 spaces but found 4                                                                                                                           indent
  11:5   error  Function 'addNumber' expected a return value                                                                                                                           consistent-return
  11:12  error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
  12:6   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
  13:1   error  Trailing spaces not allowed                                                                                                                                            no-trailing-spaces
  13:5   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
  14:24  error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
  15:18  error  There should be no spaces inside this paren                                                                                                                            space-in-parens
  15:20  error  Expected parentheses around arrow function argument                                                                                                                    arrow-parens
  15:29  error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
  16:1   error  Expected indentation of 8 spaces but found 4                                                                                                                           indent
  16:34  error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
  17:8   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
  18:1   error  Trailing spaces not allowed                                                                                                                                            no-trailing-spaces
  18:5   error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
  19:50  error  Trailing spaces not allowed                                                                                                                                            no-trailing-spaces
  19:51  error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
  20:35  error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
  21:9   error  'outputArray' is never reassigned. Use 'const' instead                                                                                                                 prefer-const
  21:26  error  Expected linebreaks to be 'LF' but found 'CRLF'                                                                                                                        linebreak-style
  22:1   error  Trailing spaces not allowed                                                                                                                                            no-trailing-spaces
  22:5   error  Expected linebreaks to be 'LF' but [...]

2019-10-14 07:04 UTC, AlexNg9 commented on index.js
> +function isSomeArrayValueNaN(item) {
Вообще, есть метод isNaN, но у него внутренняя логика отличается от вашей, поэтому некорректно называть так функцию, если она проверяет не совсем то, что нужно.

2019-10-14 07:04 UTC, AlexNg9 commented on index.js
> +function isSomeArrayValueNaN(item) {
И эта функция даже не используется.

2019-10-14 07:11 UTC, ghost requested changes

2019-10-14 07:11 UTC, AlexNg9 commented on index.js
> +function isSomeArrayValueNaN(item) {
И какой смысл пробрасывать аргументы в другую функцию? Можно убрать эту.

2019-10-14 07:11 UTC, AlexNg9 commented on index.js
> +    if (!isNotANumber(num) && Number.isInteger(num) && (num >= 0)) {
Проверка на число избыточна, если есть isInteger.

2019-10-14 07:11 UTC, AlexNg9 commented on index.js
> +    if (!isNotANumber(num) && Number.isInteger(num) && (num >= 0)) {
Можно сразу возвращать это выражение, так как оно принимает значение true/false.

2019-10-14 07:11 UTC, AlexNg9 commented on index.js
> +        return false;
Функция не должна возвращать false. Массив или null.
Два условия можно объединить в одно.

2019-10-14 07:11 UTC, AlexNg9 commented on index.js
> +    array.forEach((item) => {
Посмотрите на reduce.

2019-10-14 10:24 UTC, ghost requested changes

2019-10-14 10:24 UTC, AlexNg9 commented on index.js
> +    if (num >= 0) {
Можно всю логику этой функции в одну строку переписать.

2019-10-14 10:24 UTC, AlexNg9 commented on index.js
> +    let firstTerm = array.reduce((outputStr, curItem) => outputStr += curItem.toString());
Лучше в reduce всегда явно передавать начальное значение (аккумулятор).
И нет смысл делать присвоение `+=` – можно возвращать сумму.

2019-10-14 10:24 UTC, AlexNg9 commented on index.js
> +    let firstTerm = array.reduce((outputStr, curItem) => outputStr += curItem.toString());
Не понимаю смысла названия переменной.

2019-10-14 14:04 UTC, ghost approved these changes
👍

2019-10-14 14:04 UTC, ghost commented on index.js
> +    return num >= 0 ? Number.isInteger(num) : false;
Число является положительным и целым, если оно положительное **и** (&&) целое.

2019-10-14 14:04 UTC, closed without merging