firstlab
frontend-tinkoff-ekb/rtf-lab-1 pull request #34
Opened 2019-10-11 18:05 UTC by semen-kostin

2019-10-15 11:06 UTC, ghost requested changes

2019-10-15 11:06 UTC, AlexNg9 commented on index.js
> +    return Array.from(sum, (x) => Number(x));
Можно в качестве функции передать просто Number.

2019-10-15 11:06 UTC, AlexNg9 commented on index.js
> +    let sum = '';
Кажется, сюда лучше присвоить 0 изначально, чтобы ниже не приводить к числу.

2019-10-15 11:06 UTC, AlexNg9 commented on index.js
> +    sum = (Number(sum) + number).toString().split('');
Плохо так перезаписывать значение. Было число, а теперь массив.

2019-10-17 14:00 UTC, kosseman commented on index.js
> +    let sum = '';
Я попробовал, но получилось так, что, если я присваиваю sum нулю, выводится арифметическая сумма всех элементов входного массива и 2-го аргумента. Решил оставить как есть. Остальное исправлено.

2019-10-17 14:07 UTC, ghost commented on index.js
> +    let sum = '';
@semen-kostin перепутал с другим алгоритмом решения. Вы правы.

2019-10-17 14:08 UTC, AlexNg9 commented
👍

2019-10-17 14:08 UTC, closed without merging