Meow
frontend-tinkoff-ekb/rtf-lab-1 pull request #41
Opened 2019-10-12 15:38 UTC by Anna-Skorodskaya

2019-10-12 19:01 UTC, tiktaka commented
Привет, познакомимся? Meow

2019-10-13 05:54 UTC, Anna-Skorodskaya commented
> Привет, познакомимся? Meow



> Привет, познакомимся? Meow

Ну можно, ахах)

2019-10-13 09:24 UTC, tiktaka commented
@Anna-Skorodskaya Я Паша, я код фигашу

2019-10-13 14:58 UTC, Anna-Skorodskaya commented
> @Anna-Skorodskaya Я Паша, я код фигашу. А ты?

А я кот. Копал этот код в рот

2019-10-16 08:49 UTC, ghost requested changes

2019-10-16 08:49 UTC, AlexNg9 commented on index.js
> +    if (array.every((item) => item === 0 || item === 1 || item === 2 || item === 3
А если бы элементами массива были допустимы числа от 0 до 100? Что делать?

2019-10-16 08:49 UTC, AlexNg9 commented on index.js
> +    let stringFromArray = 0;
Здесь инициализируется числом, а ниже присваивается строка.

2019-10-16 08:49 UTC, AlexNg9 commented on index.js
> +    } else return null;
Можно взять отрицание условие и вернуть null, а ниже уже получить строку, вне условия.

2019-10-16 10:02 UTC, Anna-Skorodskaya commented on index.js
> +    if (array.every((item) => item === 0 || item === 1 || item === 2 || item === 3
Тогда проверяем, является ли число типом number и входит ли в диапазон от 0 до 100:

   if (array.every((item) => Number.isInteger(item) && item >= 0 && item <= 100 )) {
        stringFromArray = array.join('');
    } else return null;

Если массив допустимых чисел небольшой, посчитала нужным перечислить каждый из них, чтоб уж наверняка ничего лишнего не прошло. Но действительно, можно было б добиться того же результата с меньшим количеством кода.

2019-10-16 10:07 UTC, Anna-Skorodskaya commented on index.js
> +    let stringFromArray = 0;
Тогда лучше написать: 
let stringFromArray = '';

2019-10-16 10:28 UTC, Anna-Skorodskaya commented on index.js
> +    } else return null;
Исправила код с учетом всех пожеланий в новом commit

2019-10-16 10:47 UTC, AlexNg9 commented on index.js
> +    } else return null;
@Anna-Skorodskaya тесты

2019-10-16 17:18 UTC, Anna-Skorodskaya commented on index.js
> +    } else return null;
Теперь проходит

2019-10-17 06:56 UTC, ghost requested changes

2019-10-17 06:56 UTC, AlexNg9 commented on index.js
> +    if (!array.every((item) => typeof item === 'number' && item >= 0 && item <= 9)) return null;
Лучше на отдельную строку return. Так будет лучше читаемость.

2019-10-17 06:56 UTC, AlexNg9 commented on index.js
> +    let unifiedArray = 0;
array – массив. Присваиваете число.

2019-10-17 06:56 UTC, AlexNg9 commented on index.js
> +    unifiedArray = array.join('');
А тут уже строка.

2019-10-17 06:56 UTC, AlexNg9 commented on index.js
> +    if (typeof number !== 'number') return null;
Можно это вынести в начало функции к первой проверке. А можно первую проверку вынести в переменную и написать это все в один if.

2019-10-17 06:56 UTC, AlexNg9 commented on index.js
> +    const returnedArray = finalNumber.toString().split('').map(Number);
Можно это сразу вернуть.

2019-10-17 13:20 UTC, Anna-Skorodskaya commented on index.js
> +    const returnedArray = finalNumber.toString().split('').map(Number);
Все исправления внесены в новый коммит (вау! с первого раза прошел)

2019-10-17 13:41 UTC, plazmoid commented
Переживал за ваши коммиты больше, чем за свои

2019-10-17 13:58 UTC, ghost approved these changes
👍

2019-10-17 13:58 UTC, AlexNg9 commented on index.js
> +    if (!array.every((item) => typeof item === 'number' && item >= 0 && item <= 9) && typeof number === 'number') {
Довольно длинное условие. Можно было бы вынести цикл в переменную.

2019-10-17 14:02 UTC, AlexNg9 commented
В следующий раз за такое аннулирую задачу: https://github.com/frontend-tinkoff-ekb/rtf-lab-1/pull/41#issuecomment-541425535

2019-10-17 14:02 UTC, closed without merging