Решение задачи
frontend-tinkoff-ekb/rtf-lab-1 pull request #43
Opened 2019-10-12 18:14 UTC by ser9eevich

Попытка № 2

2019-10-12 18:41 UTC, frontend-tinkoff-ekb commented
1:4   error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
   2:56  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
   3:82  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
   4:3   error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
   5:36  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
   6:22  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
   7:9   error    'resultArr' is never reassigned. Use 'const' instead                          prefer-const
   7:24  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
   8:22  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
   9:22  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  10:1   error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  11:22  error    Expected '===' and instead saw '=='                                           eqeqeq
  11:27  error    Missing space before opening brace                                            space-before-blocks
  11:28  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  12:32  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  13:9   error    Expected blank line before this statement                                     padding-line-between-statements
  13:26  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  14:6   error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  15:1   error    Trailing spaces not allowed                                                   no-trailing-spaces
  15:5   error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  16:19  error    Unexpected function expression                                                prefer-arrow-callback
  16:19  warning  Unexpected unnamed function                                                   func-names
  16:27  error    Missing space before function parentheses                                     space-before-function-paren
  16:34  error    'i' is defined but never used                                                 no-unused-vars
  16:37  error    'arr' is defined but never used                                               no-unused-vars
  16:43  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  17:1   error    Expected indentation of 8 spaces but found 7                                  indent
  17:8   error    Expected { after 'if' condition                                               curly
  17:12  error    Unary word operator 'typeof' must be followed by whitespace                   space-unary-ops
  17:29  error    Strings must use singlequote                                                  quotes
  17:38  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  18:1   error    Expected indentation of 12 spaces but found 7                                 indent
  18:8   error    Expected no linebreak before this statement                                   nonblock-statement-body-position
  18:24  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  19:1   error    Expected indentation of 8 spaces but found 7                                  indent
  19:8   error    Expected { after 'else'                                                       curly
  19:12  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  20:1   error    Expected indentation of 12 spaces but found 7                                 indent
  20:8   error    Expected no linebreak before this statement                                   nonblock-statement-body-position
  20:20  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  21:8   error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  22:1   error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  23:23  error    Missing space before opening brace                                            space-before-blocks
  23:24  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  24:21  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  25:5   error    Closing curly brace does not appear on the same line as the subsequent block  brace-style
  25:6   error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  26:5   error    Expected space(s) after "else"                                                keyword-spacing
  26:9   error    Unnecessary 'else' after 'return'                                             no-else-return
  26:10  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  27:24  error    Missing radix parameter                                                       radix
  27:42  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  28:32  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  29:9   error    'resultStr' is not defined                                                    no-undef
  29:42  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  30:1   error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  31:29  error    'resultStr' is not defined                                                    no-undef
  31:53  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  32:1   error    Expected indentation of 12 spaces but found 8                                 indent
  32:24  error    Missing radix parameter                                                       radix
  32:33  error    'resultStr' is not defined                                                    no-undef
  32:47  error    Missing semicolon                                                             semi
  32:47  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  33:1   error    Expected indentation of 8 spaces but found 4                                  indent
  33:6   error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  34:6   error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  35:5   error    Expected blank line before this statement                                     padding-line-between-statements
  35:22  error    Trailing spaces not allowed                                                   no-trailing-spaces
  35:25  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  36:2   error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  37:1   error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
  38:19  error    Expected linebreaks to be 'LF' but found 'CRLF'                               linebreak-style
 [...]

2019-10-13 14:10 UTC, ghost requested changes

2019-10-13 14:10 UTC, AlexNg9 commented on index.js
> +        if (typeof (item) === 'number') origStr += item;
Лучше провалидировать массив заранее, а тут можно использовать другой метод массива. Даже два.

2019-10-13 14:10 UTC, AlexNg9 commented on index.js
> +    if (fail === true) {
Нет смысла булеву переменную проверять в явном виде, если вы знаете, что там точно булево значение.

2019-10-13 14:10 UTC, AlexNg9 commented on index.js
> +    let fail = false;
Эта переменная лишняя, нужно переписать без нее.

2019-10-13 14:10 UTC, AlexNg9 commented on index.js
> +    resultNumber = parseInt(origStr, 10);
Можно объявлять переменную прямо здесь, а не выше.

2019-10-13 14:10 UTC, AlexNg9 commented on index.js
> +    resultStr = String(resultNumber);
Аналогично можно объявить здесь.

2019-10-13 14:10 UTC, AlexNg9 commented on index.js
> +    for (let i = 0; i < resultStr.length; i++) {
Посмотрите на метод map.

2019-10-13 18:05 UTC, ser9eevich commented
Исправил весь код, вроде работает

2019-10-14 10:37 UTC, ghost requested changes

2019-10-14 10:37 UTC, AlexNg9 commented on index.js
> +    if (checkArr) {
Если взять обратное условие, то можно не делать такую логику внутри условия, а вернуть тут null.
Так лучше читаемость.

2019-10-14 10:37 UTC, AlexNg9 commented on index.js
> +    const checkArr = array.every((item) => typeof (item) === 'number');
Название не помогает понять, что проверяли. Например, то, что каждый элемент число.

2019-10-14 10:37 UTC, AlexNg9 commented on index.js
> +        if (array.length === 0) {
Такой ситуации не предусмотрено. Наверное, даже должен быть null даже в таком случае, так как мы прибавляем число к "пустоте".

2019-10-14 10:37 UTC, AlexNg9 commented on index.js
> +            return resultArr;
Можно просто вернуть `[number]`;

2019-10-14 10:37 UTC, AlexNg9 commented on index.js
> +        let resultArr = [];
Объявление переменной можно перенести вниз.

2019-10-14 10:37 UTC, AlexNg9 commented on index.js
> +        origNum += number;
Можно и сразу прибавить. Тогда переменная будет const.

2019-10-14 10:37 UTC, AlexNg9 commented on index.js
> +        resultArr = resultArr.map((item) => parseInt((item), 10));
Можно на предыдущую строку. Либо на предыдущей строке создать новую переменную с осмысленным названием. Но вот так перезаписывать не нужно. Получается, что в разные моменты времени в переменной содержатся разные по смыслу значения.

2019-10-14 11:57 UTC, ser9eevich commented on index.js
> +            return resultArr;
@AlexNg9 Но по условию метод должен возвращать массив, а если мы вернем `[number]`, то получается решение задачи будет не верным?

2019-10-15 06:55 UTC, ghost requested changes

2019-10-15 06:55 UTC, AlexNg9 commented on index.js
> +    if (allElementsAreNumbers && array.length !== 0) {
Лучше взять отрицание этого условия и вернуть в if null.

2019-10-15 06:55 UTC, AlexNg9 commented on index.js
> +        const stringArr = numStr.split('');
Лучше подробнее называть. `digitStringArray`, например.

2019-10-15 06:55 UTC, AlexNg9 commented on index.js
> +        const resultArr = stringArr.map((item) => parseInt((item), 10));
Можно сразу вернуть эту строку, не заводя переменную.

2019-10-15 07:07 UTC, ser9eevich commented on index.js
> +        const resultArr = stringArr.map((item) => parseInt((item), 10));
Я хотел так сделать, но думал что это неправильно

2019-10-15 08:13 UTC, ser9eevich commented on index.js
> +    if (allElementsAreNumbers && array.length !== 0) {
Можете объяснить почему так лучше? Это если массив попадется не удовлетворяющий условию, сразу вернуть `null`, а не проходить весь код?

2019-10-15 08:15 UTC, ser9eevich commented on index.js
> +        const resultArr = stringArr.map((item) => parseInt((item), 10));
После данного исправления, вылезли ошибки  13:5   error  Return statement should not contain assignment       no-return-assign
  13:12  error  'resultArr' is not defined                           no-undef
  13:38  error  Expected parentheses around arrow function argument  arrow-parens

2019-10-15 09:57 UTC, ghost approved these changes
👍

2019-10-15 09:57 UTC, closed without merging