Решение
frontend-tinkoff-ekb/rtf-lab-1 pull request #47
Opened 2019-10-12 19:51 UTC by baygulovd

2019-10-13 14:07 UTC, ghost requested changes

2019-10-13 14:07 UTC, AlexNg9 commented on index.js
> +    if (!Array.isArray(array) || !Number.isInteger(number) || number < 0) { return null; }
Если есть фигурные скобки – переносим на новую строку действие по условию.

2019-10-13 14:07 UTC, AlexNg9 commented on index.js
> +        } else if ((typeof (array[i]) === 'string' || array[i] === null)) {
Если предыдущее условие не прошло, то зачем делать эти проверки?

2019-10-13 14:07 UTC, AlexNg9 commented on index.js
> +    if (array.length === 0) {
Это условие можно вынести в самое начало тогда.

2019-10-13 14:07 UTC, AlexNg9 commented on index.js
> +    for (let i = 0; i < res.length; i++) {
Посмотрите на метод map.

2019-10-14 10:49 UTC, ghost requested changes

2019-10-14 10:49 UTC, AlexNg9 commented on index.js
> +        return arr;
Можно выше переменную не объявлять, а сразу [number].

2019-10-14 10:49 UTC, AlexNg9 commented on index.js
> +        if (array[i] >= 0 && Number.isInteger(array[i]) && typeof (array[i]) !== 'string' && array[i] != null) {
Попробуйте разделить проверку массива и получение числа из него. Используйте методы массива.

2019-10-14 10:49 UTC, AlexNg9 commented on index.js
> +    const res = intNumber.toString();
Плохое название.

2019-10-14 10:49 UTC, AlexNg9 commented on index.js
> +    for (let i = 0; i < res.length; i++) {
Лучше использовать join или reduce.

2019-10-14 10:49 UTC, AlexNg9 commented on index.js
> +    const result = arr.map((item) => parseInt(item, 10));
Можно сразу вернуть результат выражения.

2019-10-14 12:03 UTC, baygulovd commented
переписал полностью, используя функции

2019-10-14 14:36 UTC, ghost approved these changes
👍

2019-10-14 14:36 UTC, AlexNg9 commented on index.js
> +    if (array == null || number < 0 || number == null
Используем строгое равенство (===).

2019-10-14 14:36 UTC, closed without merging