Task1
frontend-tinkoff-ekb/rtf-lab-1 pull request #54
Opened 2019-10-13 08:37 UTC by RexMaleficus

Решение

2019-10-13 14:03 UTC, ghost requested changes

2019-10-13 14:03 UTC, AlexNg9 commented on index.js
> +    arrayNumber += array[array.length - 1];
А что если строки в цикле поменять местами? Кажется, что тогда не нужна будет эта строка.

2019-10-13 14:03 UTC, AlexNg9 commented on index.js
> +        if (typeof array[i] === 'number') {
Для проверки какого-то условия на всех элементах массива есть специальный метод.

2019-10-13 14:04 UTC, RexMaleficus commented on index.js
> +        if (typeof array[i] === 'number') {
for (item in array)?

2019-10-13 14:05 UTC, RexMaleficus commented on index.js
> +    arrayNumber += array[array.length - 1];
А это обязательно?) Мне и так нравится

2019-10-13 14:39 UTC, AlexNg9 commented on index.js
> +        if (typeof array[i] === 'number') {
Методом называется то, что вызывается от объекта.
`array.methodName()`

2019-10-13 14:41 UTC, ghost requested changes

2019-10-13 14:41 UTC, AlexNg9 commented on index.js
> +    arrayNumber += array[array.length - 1];
Выглядит неаккуратно, но ок.

2019-10-14 05:50 UTC, ghost approved these changes

2019-10-14 05:50 UTC, AlexNg9 commented on index.js
> +    const isCorrect = (element) => typeof element === 'number' && element >= 0 && element <= 9;
👍

2019-10-14 05:50 UTC, AlexNg9 commented
👍

2019-10-14 05:50 UTC, closed without merging