Solution (version 1.0)
frontend-tinkoff-ekb/rtf-lab-1 pull request #56
Opened 2019-10-13 11:25 UTC by ADPopov

2019-10-13 14:00 UTC, ghost requested changes

2019-10-13 14:00 UTC, AlexNg9 commented on index.js
> +    return (number !== 'string')
Ниндзя-код – далеко не всегда хорошо.
Разбейте на строки, вынесите что-то в переменные.

2019-10-13 15:14 UTC, ghost requested changes

2019-10-13 15:14 UTC, AlexNg9 commented on index.js
> +    return number !== 'string';
Кроме строк и чисел, есть и другие типы.

2019-10-13 15:14 UTC, AlexNg9 commented on index.js
> +    let secondNumberIsNumber = isNumber(number);
Второе число? Да оно вроде одно передается. Лучше иначе назвать.

2019-10-13 15:14 UTC, AlexNg9 commented on index.js
> +    return secondNumberIsNumber && arrayElementsIsNumber ? arr : null;
Странно проделать все операции вычислительные, а потом возвращать null, если условия не прошли. Можно до вычислений это сделать.

2019-10-14 10:44 UTC, ghost requested changes

2019-10-14 10:44 UTC, AlexNg9 commented on index.js
> +    const arrayElementsIsNumber = array.every((item) => (typeof item === 'number' && (item >= 0) && (item <= 9)));
Обычно булевы переменные в таком стиле называют `isCondition...`. is идет вначале.

2019-10-14 10:44 UTC, AlexNg9 commented on index.js
> +    const arrayElementsIsNumber = array.every((item) => (typeof item === 'number' && (item >= 0) && (item <= 9)));
Много скобок лишних. Вроде внутри функции вообще скобки не нужны.

2019-10-14 10:44 UTC, AlexNg9 commented on index.js
> +    const NumberIsNumber = typeof (number) === 'number';
Скобки лишние, если используете как оператор, а не как функцию.

2019-10-14 10:44 UTC, AlexNg9 commented on index.js
> +    if (arrayElementsIsNumber && NumberIsNumber) {
NumberIsNumber 😨 
И по комменту выше еще тогда isNumberNumber, чтоб точно.

2019-10-14 11:10 UTC, ADPopov commented on index.js
> +    if (arrayElementsIsNumber && NumberIsNumber) {
Я не знаю как назвать проверку что число которое мы вводим имеет тип числа...

2019-10-14 11:50 UTC, AlexNg9 commented on index.js
> +    if (arrayElementsIsNumber && NumberIsNumber) {
В данном случае условие простое и не составное, поэтому из самого выражения очевиден смысл.
Это как: `isNumberPositive = number > 0`.
Можно прямо в if его написать.

2019-10-14 11:52 UTC, ghost approved these changes

2019-10-14 11:52 UTC, AlexNg9 commented on index.html
> +<!DOCTYPE HTML>
Зачем?

2019-10-14 11:52 UTC, AlexNg9 commented on package.json
> +  "description": "Нужно реализовать функцию, которая будет принимать два аргумента. Первый аргумент - массив, состоящий из цифр от 0 до 9. Второй - любое целое положительное число. Метод должен возвр
Зачем?

2019-10-14 11:52 UTC, AlexNg9 commented
👍

2019-10-14 11:52 UTC, closed without merging