master
frontend-tinkoff-ekb/rtf-lab-1 pull request #57
Opened 2019-10-13 12:05 UTC by NickOzr211

2019-10-13 14:49 UTC, NickOzr211 commented
да ладно, вау
неужели

2019-10-13 14:53 UTC, ghost requested changes

2019-10-13 14:53 UTC, AlexNg9 commented on index.js
> +            || number < 0
Зачем в цикле каждый раз проверять переменную, которая не меняется?

2019-10-13 14:53 UTC, AlexNg9 commented on index.js
> +    for (let i = 0; i < array.length; i++) {
Используйте специальный метод массива для проверки.

2019-10-13 14:53 UTC, AlexNg9 commented on index.js
> +    resultNumber = parseInt(array.toString().replace(/,/gi, ''), 10);
Не надо так делать. Используйте другой способ получения строки из массива.

2019-10-14 05:48 UTC, ghost approved these changes

2019-10-14 05:48 UTC, AlexNg9 commented on index.js
> +    || element > 9
Форматирование кривое. Наверное, условие в some ну одну строку, а все остальные на следующую, либо все остальные на отдельных строках.

2019-10-14 05:49 UTC, AlexNg9 commented
👍

2019-10-14 05:49 UTC, closed without merging