Task1
frontend-tinkoff-ekb/rtf-lab-1 pull request #59
Opened 2019-10-13 12:49 UTC by TiDebilHAHAHA

Реализованная функция из 1ой лабы

2019-10-13 13:58 UTC, ghost requested changes

2019-10-13 13:58 UTC, AlexNg9 commented on index.js
> +        if (typeof array[i] !== 'number' || array[i] > 9 || array[i] < 0) {
Используйте специальный метод массива для этого.

2019-10-13 13:58 UTC, AlexNg9 commented on index.js
> +    const arr = parseInt(array.toString().replace(/,/gm, ''), 10);
Не стоит так получать число из массива. Есть другой способ получить строку из массива. Посмотрите на методы массива.

2019-10-13 13:58 UTC, AlexNg9 commented on index.js
> +    return Array.from(String(result), Number);
Что-то новое 👍

2019-10-13 15:49 UTC, TiDebilHAHAHA commented on index.js
> +        if (typeof array[i] !== 'number' || array[i] > 9 || array[i] < 0) {
Скажите что за метод пож❤️

2019-10-14 08:17 UTC, TiDebilHAHAHA commented
я нормально так назакрывал проектов, больше не буду, не знал, что нельзя

2019-10-14 09:02 UTC, TiDebilHAHAHA commented
Не знал что есть такая штука тут

2019-10-14 10:31 UTC, ghost approved these changes
👍

2019-10-14 10:31 UTC, closed without merging