task1
frontend-tinkoff-ekb/rtf-lab-1 pull request #61
Opened 2019-10-13 13:47 UTC by oceanvievv

2019-10-13 14:33 UTC, ghost requested changes

2019-10-13 14:33 UTC, AlexNg9 commented on index.js
> +        if (typeof array[i] !== 'number' || array[i] > 9 || array[i] < 0) {
Можно сразу возвращать выражение внутри if, а не булевы значения в явном виде.

2019-10-13 14:33 UTC, AlexNg9 commented on index.js
> +        if (typeof array[i] !== 'number' || array[i] > 9 || array[i] < 0) {
Вообще у массива есть специальные методы, которые проверяют все элементы на какое-то условие.

2019-10-13 14:33 UTC, AlexNg9 commented on index.js
> +    if (!isCorrectArray(array) || !isCorrectNumber(number)) {
Разбиение на функции 👍

2019-10-13 14:33 UTC, AlexNg9 commented on index.js
> +        .replace(/[^0-9]/gm, ''), 10);
Так делать не нужно. Попробуйте иначе получить строку из массива. Есть специальный метод.

2019-10-14 16:01 UTC, oceanvievv commented on index.js
> +        if (typeof array[i] !== 'number' || array[i] > 9 || array[i] < 0) {
> Вообще у массива есть специальные методы, которые проверяют все элементы на какое-то условие.

Что за "специальный метод"?

2019-10-15 10:02 UTC, AlexNg9 commented on index.js
> +        if (typeof array[i] !== 'number' || array[i] > 9 || array[i] < 0) {
Посмотрите, какие у массивов есть методы для перебора массива. forEach, map и тд
Выберите нужный.

2019-10-22 06:29 UTC, closed without merging