first task
frontend-tinkoff-ekb/rtf-lab-1 pull request #62
Opened 2019-10-13 13:48 UTC by veetash

2019-10-13 14:36 UTC, ghost requested changes

2019-10-13 14:36 UTC, AlexNg9 commented on index.js
> +    array.forEach((element) => {
Есть метод у массива, который проверяет все элементы на какое-то условие.

2019-10-13 14:36 UTC, AlexNg9 commented on index.js
> +        if (element >= 0 && element <= 9 && Number.isInteger(element)) {
Лучше отдельно провалидировать массив, а потом получить из него строку.

2019-10-13 14:36 UTC, AlexNg9 commented on index.js
> +    num = parseInt(str, 10);
Можно на этой строке объявить переменную.

2019-10-13 14:36 UTC, AlexNg9 commented on index.js
> +    lastnum = num.toString();
Аналогично.

2019-10-13 14:36 UTC, AlexNg9 commented on index.js
> +    for (let i = 0; i < lastnum.length; i++) {
Посмотрите на метод map.

2019-10-13 14:36 UTC, AlexNg9 commented on index.js
> +    if (flag === false) return arr;
От флага нужно избавиться.

26 и 28 строку можно, но не нужно, переписать с тернарным оператором:
`flag ? null : arr`

2019-10-14 10:28 UTC, ghost requested changes

2019-10-14 10:28 UTC, AlexNg9 commented on index.js
> +    const flag = array.every((element) => (element >= 0
Название переменной не помогает понять, что мы проверяли. Скобки вокруг выражения-условия лишние.
Можно и в одну строку, либо каждую проверку на отдельной.

2019-10-14 10:28 UTC, AlexNg9 commented on index.js
> +    array.forEach((element) => {
Посмотрите на reduce.

2019-10-14 10:28 UTC, AlexNg9 commented on index.js
> +    num += number;
Можно в предыдущей строке сразу прибавить.

2019-10-14 10:28 UTC, AlexNg9 commented on index.js
> +    const lastnum = num.toString();
Название переменных в camelCase.

2019-10-14 10:28 UTC, AlexNg9 commented on index.js
> +    if (flag === true) return arr;
Избавиться от флага.

2019-10-15 06:56 UTC, ghost requested changes

2019-10-15 06:56 UTC, AlexNg9 commented on index.js
> +    if (array.every((element) => element >= 0
Плохое форматирование условия, сложно читается. Лучше выделить в переменную эту проверку.

2019-10-15 06:56 UTC, AlexNg9 commented on index.js
> +        arr = arr.map((lastN) => parseInt(lastN, 10));
lastN – непонятное название.
Можно вернуть сразу этот результат, без переприсваивания.

2019-10-15 12:46 UTC, veetash commented
checkIsTrue пришлось записывать в таком виде, т.к. никак по-другому eslint не хочет принимать

2019-10-16 13:48 UTC, ghost approved these changes
👍

2019-10-16 13:48 UTC, AlexNg9 commented on index.js
> +    const checkIsTrue = array.every((element) => element >= 0
Плохое название переменной. Не помогает понять, что мы проверяли. isArrayValid, как пример.

2019-10-16 13:48 UTC, AlexNg9 commented on index.js
> +    if (checkIsTrue) {
Лучше тут взять отрицание условие и вернуть null, а после условия текущую логику прописать.

2019-10-16 13:48 UTC, closed without merging