task#1
frontend-tinkoff-ekb/rtf-lab-1 pull request #66
Opened 2019-10-13 15:41 UTC by d-kuvashov

2019-10-15 11:11 UTC, ghost requested changes

2019-10-15 11:11 UTC, AlexNg9 commented on index.js
> +        if (typeof (array[i]) !== 'number' || array[i] < 0 || array[i] > 9) {
Посмотрите, какой метод массива можно использовать для такой логики.

2019-10-15 11:11 UTC, AlexNg9 commented on index.js
> +    let helperNum = 0;
Плохое название переменной.

2019-10-15 11:11 UTC, AlexNg9 commented on index.js
> +    const newArray = [];
Плохое название переменной.

2019-10-15 11:11 UTC, AlexNg9 commented on index.js
> +    if (number < 0 || Number.isInteger(number) === false) {
isInteger возвращает true/false. Не нужно проверять его дополнительно.

2019-10-15 11:11 UTC, AlexNg9 commented on index.js
> +        j++;
Можно вынести это в цикл. i--, j++.

2019-10-15 11:11 UTC, AlexNg9 commented on index.js
> +    let helperCount = 0;
Плохое название переменной.

2019-10-15 19:21 UTC, d-kuvashov commented on index.js
> +        j++;
Здравствуйте, код исправил

2019-10-16 08:54 UTC, ghost requested changes

2019-10-16 08:54 UTC, AlexNg9 commented on index.js
> +        if (typeof (item) !== 'number' || item < 0 || item > 9) {
У массива есть метод, который позволяет проверить условие для всех его элементов.

2019-10-16 08:54 UTC, AlexNg9 commented on index.js
> +    let check;
Флаг избыточен.

2019-10-16 08:54 UTC, AlexNg9 commented on index.js
> +        result[0] = 0;
Можно result = [0]

2019-10-16 08:54 UTC, AlexNg9 commented on index.js
> +    while (x >= 1) {
Кажется, это лишние действия. Это должны быть в нижнем цикле, либо вообще без этого.
В этом цикле ищется логарифм x по основанию 10. Можно использовать метод Math.log для этого.

2019-10-16 15:07 UTC, d-kuvashov commented on index.js
> +        if (typeof (item) !== 'number' || item < 0 || item > 9) {
Здравствуйте, имеется в виду reduce? Просто forEach ведь тоже проверяет условия для всех элементов.

2019-10-16 15:20 UTC, d-kuvashov commented on index.js
> +    while (x >= 1) {
Исправил всё, кроме метода проверки массива

2019-10-16 15:26 UTC, d-kuvashov commented on index.js
> +        if (typeof (item) !== 'number' || item < 0 || item > 9) {
Или every?

2019-10-17 06:48 UTC, AlexNg9 commented on index.js
> +        if (typeof (item) !== 'number' || item < 0 || item > 9) {
- reduce – позволяет из массива и стартового значения получить какой-то конечный результат. Можно назвать это суммой. Можно собрать новый массив, новый объект, на основе текущего массива. Тогда стартовыми значениями будут [] и {} соответственно.
- forEach – ничего не проверяет. Этот метод позволяет пройтись по всем элементам массива. Он не возвращает никакого результата.
- every – проверяет, возвращает boolean. Аналогично есть метод some.

2019-10-17 06:52 UTC, ghost requested changes

2019-10-17 06:52 UTC, AlexNg9 commented on index.js
> +    if (number < 0 || !Number.isInteger(number)) {
Почему бы не использовать isInteger также выше?

2019-10-17 06:52 UTC, AlexNg9 commented on index.js
> +    if (array.length === 0) {
Можно выделить все проверки в переменные и написать один if.

2019-10-17 06:52 UTC, AlexNg9 commented on index.js
> +    let result = [];
Если не собираетесь переприсвоить массив, можно через const.

2019-10-17 06:52 UTC, AlexNg9 commented on index.js
> +        result = [0];
Тут можно сразу вернуть результат же. Условие sum >= 1 не выполнится.

2019-10-17 06:52 UTC, AlexNg9 commented on index.js
> +    let count = 0;
count – количество. Тут скорее речь об индексах.

2019-10-18 03:45 UTC, d-kuvashov commented on index.js
> +    if (number < 0 || !Number.isInteger(number)) {
Здравствуйте, тогда код не будет считать дробные числа. Остальное исправил

2019-10-18 06:48 UTC, AlexNg9 commented on index.js
> +    if (number < 0 || !Number.isInteger(number)) {
По условию задачи в массиве цифры от 0 до 9. number – целое. Дробей нет.

2019-10-18 06:51 UTC, ghost approved these changes
👍

2019-10-18 06:51 UTC, AlexNg9 commented on index.js
> +    if (array.length === 0 || number < 0 || !Number.isInteger(number) || !array.every((item) => typeof (item) === 'number' && item >= 0 && item <= 9)) {
Очень длинное сложное условие. Проверку number можно выделить в отдельную переменную. Цикл тоже.

2019-10-18 06:51 UTC, ghost commented on index.js
> +    let sum = 0;
Лучше объявить ближе к месту использования переменные.

2019-10-18 06:52 UTC, closed without merging