Task 1(addNumber)
frontend-tinkoff-ekb/rtf-lab-1 pull request #7
Opened 2019-10-07 13:56 UTC by dartrhevan

2019-10-07 14:18 UTC, AlexNg9 commented
@dartrhevan подтяните, пожалуйста, изменения из master ветки
`git pull [путь до репозитория] master`

2019-10-07 14:29 UTC, dartrhevan commented
сделал

2019-10-07 14:31 UTC, ghost requested changes

2019-10-07 14:31 UTC, AlexNg9 commented on index.js
> +        if(!Number.isInteger(digit) || digit > 9 || digit < 0)
👍

2019-10-07 14:31 UTC, AlexNg9 commented on index.js
> +    for(let i = 0; i < array.length; ++i) {
Если здесь написать i++, то в строке `base += Math.pow(10, array.length - i - 1) * digit;` вроде можно будет убрать - 1

2019-10-07 14:31 UTC, AlexNg9 commented on index.js
> +        base += Math.pow(10, array.length - i - 1) * digit;
`Math.pow(base, power)` можно заменить на `base ** power` (10 ** 3 = 1000)

2019-10-07 14:31 UTC, AlexNg9 commented on index.js
> +    let resultNumber = base + number, result = [];
Лучше объявление каждой переменной писать с новой строки, иначе можно не заметить ее

2019-10-07 14:31 UTC, AlexNg9 commented on index.js
> +    while(resultNumber > 0);
Конструкцию do while не используют в современной разработке. Попробуйте переписать через обычный while.

2019-10-07 14:31 UTC, AlexNg9 commented on index.js
> +    for(let i = 0; i < array.length; ++i) {
И в целом циклы со счетчиком обычно пишут с инкрементом `i++`

2019-10-07 14:31 UTC, AlexNg9 commented on index.js
>  };
В конце файлов обычно принято добавлять пустую строку, на что так же указывает Github.
Добавим правило в lint.

2019-10-07 14:43 UTC, dartrhevan commented on index.js
> +    for(let i = 0; i < array.length; ++i) {
-1 убрать не получиться

2019-10-07 14:51 UTC, dartrhevan commented
исправил всё, кроме -1(заменой инкремента её убрать не получиться)

2019-10-07 15:22 UTC, dartrhevan reviewed
исправил всё, кроме -1(заменой инкремента её убрать не получиться)

2019-10-07 15:25 UTC, dartrhevan reviewed
исправил: заменил инкремент, убрал do while и Math.pow, добавил пустую строку, переместил объявление переменной

2019-10-09 07:15 UTC, ghost requested changes

2019-10-09 07:15 UTC, AlexNg9 commented on index.js
> +    for(;;) {
Это тоже не совсем то.

2019-10-09 07:15 UTC, AlexNg9 commented on index.js
> +        if(resultNumber <= 0) break;
На самом деле из условия задачи не может быть ситуации, что при `resultNumber -= digit` получится `resultNumber < 0`.
Подумайте какой крайний случай ломает алгоритм (цикл) и вынесете необходимую проверку за цикл. Тогда ему можно будет вернуть старый вид через `while`.

2019-10-09 07:15 UTC, AlexNg9 commented on index.js
> +    let result = [];
Можно объявить через const, т.к. значение не будет присваиваться еще раз.

2019-10-09 07:15 UTC, AlexNg9 commented on index.js
> +    }
Ставим отступы в виде пустой строки вокруг for/if/while.

2019-10-09 07:41 UTC, dartrhevan commented on index.js
> +        if(resultNumber <= 0) break;
Я вроде так уже пробовал, но не получилось

2019-10-09 07:58 UTC, dartrhevan commented
добавил отступы, const и while

2019-10-09 08:34 UTC, ghost requested changes

2019-10-09 08:34 UTC, AlexNg9 commented on index.js
> +    if(resultNumber == 0) return [0];
Пробелы после if/while, строгое сравнение ===.
Лучше переносить действие для условия на отдельную строку и в фигурные скобки брать.

2019-10-09 08:34 UTC, AlexNg9 commented on index.js
> +    for(let i = 0; i < array.length; i++) {
Давайте попробуем разбить проверку валидности массива и суммирования чисел в нем на две отдельные операции. Для этого у массива есть удобные методы.

2019-10-09 09:20 UTC, ghost approved these changes

2019-10-09 09:20 UTC, AlexNg9 commented on index.js
> +    if(array.some(digit => !Number.isInteger(digit) || digit > 9 || digit < 0)){
👍

2019-10-09 09:20 UTC, AlexNg9 commented on index.js
> +    array.forEach((digit, i) =>{
Вообще, я имел в виду reduce, скорее, но так тоже нормально.

2019-10-09 09:20 UTC, AlexNg9 commented on index.js
> +    if(array.some(digit => !Number.isInteger(digit) || digit > 9 || digit < 0)){
Пробелов не хватает снова.

2019-10-09 09:21 UTC, closed without merging

2019-10-09 09:23 UTC, AlexNg9 commented
Хорошо!
Нетипичное решение, воображаемый плюс за это. 👍

2019-10-09 09:28 UTC, dartrhevan commented on index.js
> +    array.forEach((digit, i) =>{
С reduce проблема в том, что мне нужен индекс i -

2019-10-09 09:32 UTC, AlexNg9 commented on index.js
> +    array.forEach((digit, i) =>{
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

reduce третьим индексом пробрасывает индекс в callback.