Лабораторная работа 1
frontend-tinkoff-ekb/rtf-lab-1 pull request #76
Opened 2019-10-14 07:07 UTC by AlyonaTes

2019-10-15 06:43 UTC, ghost requested changes

2019-10-15 06:43 UTC, AlexNg9 commented on index.js
> +    do {
Не стоит использовать do-while. Перепишите с помощью методы массива.

2019-10-15 13:37 UTC, AlyonaTes commented on index.js
> +    do {
Хорошо, это через foreach или можно использовать while или for?

2019-10-16 09:01 UTC, AlexNg9 commented on index.js
> +    do {
@AlyonaTes для валидации массива можно использовать some. Для получение числа – reduce, например.

2019-10-18 06:54 UTC, ghost approved these changes
👍

2019-10-18 06:54 UTC, ghost commented on index.js
> +    const final = array.every((item) => typeof (item) === 'number');
Название переменной непонятное.

2019-10-18 06:54 UTC, closed without merging