task1
frontend-tinkoff-ekb/rtf-lab-1 pull request #80
Opened 2019-10-14 10:07 UTC by kozhezhopa

2019-10-15 07:04 UTC, AlexNg9 commented
> !!!!ПРОЧИТАЙТЕ!!!!
> короче с одногруппником работали с одного компа. когда он сделал, я сел, с репозиторием мы разобрались, просто новую папку создали и туда скопировали мой репозиторий, я залогинился в github dekstop под своим именем, но там в одной графе забыл поменять и поэтому первые два коммита были под его ником
> 
> но вопрос остается
> тут почему-то осталось сообщение, что коммитится под его ником, как поменять? нам просто постоянно так надо будет работать (на одном компе), и типа не кайф
> 
> или это оттого что первым коммит был от его ника и поэтому все так и осталось?
> UPD появилась новая проблема: там 2 participants

В вашей ветке есть его коммиты, поэтому так отображается.
Впредь будьте внимательнее.

2019-10-15 07:07 UTC, ghost requested changes

2019-10-15 07:07 UTC, AlexNg9 commented on index.js
> +    let finalNumber = 0;
Плохое название для переменной.

2019-10-15 07:07 UTC, AlexNg9 commented on index.js
> +    for (let i = 0; i < array.length; i++) {
Разделите валидацию массива и получение числа на два цикла. Используйте методы массива.

2019-10-15 07:07 UTC, AlexNg9 commented on index.js
> +    for (let i = (finalNumber.toString()).length; i > 0; i--) {
Скобки лишние перед length.

2019-10-17 07:10 UTC, ghost requested changes

2019-10-17 07:10 UTC, AlexNg9 commented on index.js
> +    const finalArr = [];
Лучше объявить ближе к месту использования.

2019-10-17 07:10 UTC, AlexNg9 commented on index.js
> +        if (!(typeof (array[i]) === 'number') || !(array[i] >= 0) || !(array[i] <= 9)) {
`!(array[i] >= 0) => array[i] < 0`
Аналогично для 9.

`!(typeof (array[i]) === 'number') => typeof (array[i]) !== 'number'`

2019-10-17 07:10 UTC, AlexNg9 commented on index.js
> +    for (let i = 0; i < array.length; i++) {
Вы не разделили на два цикла. Метод не использовали.

2019-10-19 11:20 UTC, ghost requested changes

2019-10-19 11:20 UTC, AlexNg9 commented on index.js
> +        item.toString();
в чем смысл этого вызова?

2019-10-19 11:20 UTC, AlexNg9 commented on index.js
> +    array.forEach((item) => {
Посмотрите на reduce.

2019-10-19 11:20 UTC, AlexNg9 commented on index.js
> +    if (array.some((item) => (typeof (item) !== 'number' || item < 0 || item > 9))) return null;
Лучше на отдельную строку return, так лучше читаемость.

2019-10-19 16:58 UTC, kozhezhopa commented on index.js
> +        item.toString();
я хотел перевести все элементы массива в строку, чтобы потом их сложить

2019-10-19 17:18 UTC, AlexNg9 commented on index.js
> +        item.toString();
toString – возвращает значение, но исходный объект никак не меняет. Значение вы никуда не сохраняете. Этот вызов ничего не делает по итогу.

2019-10-20 14:54 UTC, ghost approved these changes
👍

2019-10-20 14:54 UTC, AlexNg9 commented on index.js
> +    const initialValue = '';
Можно не выносить это в переменную, а просто передать аргументом пустую строку.

2019-10-20 14:54 UTC, AlexNg9 commented on index.js
> +    arrayAsString = parseInt(arrayAsString, 10) + number;
Тут это уже не массив, а число. Нужна новая переменная.

2019-10-20 14:55 UTC, closed without merging

2019-10-20 14:58 UTC, kozhezhopa commented on index.js
> +    arrayAsString = parseInt(arrayAsString, 10) + number;
а почему лаба помечена как скопированная?

2019-10-20 15:06 UTC, kozhezhopa commented on index.js
> +    arrayAsString = parseInt(arrayAsString, 10) + number;
![image](https://user-images.githubusercontent.com/56520528/67161515-b7633980-f374-11e9-9262-ea37d11b2890.png)
![image](https://user-images.githubusercontent.com/56520528/67161522-c813af80-f374-11e9-98bf-a8971cb859f3.png)
если это из-за чужих коммитов, изначально я залогинился только в свой гитхабовский акк, потом заметил, что коммитится под его ником, и узнал про вторую графу, и после этого залогинился и там. это тупо из-за того, что первый раз с этой утилитой работали

2019-10-20 15:13 UTC, kozhezhopa commented on index.js
> +    arrayAsString = parseInt(arrayAsString, 10) + number;
если лабу надо будеть защитить - без проблем, только скажите когда и где

2019-10-21 06:51 UTC, AlexNg9 commented on index.js
> +    arrayAsString = parseInt(arrayAsString, 10) + number;
@kozhezhopa мы говорили, что если у вас в пре чужие коммиты, дадим в этот раз половину баллов. В следующий – аннулируем сразу.