first task
frontend-tinkoff-ekb/rtf-lab-1 pull request #82
Opened 2019-10-14 10:17 UTC by SerGeKon

first task

2019-10-14 10:48 UTC, SerGeKon commented on index.js
> +    const resultString = result.toString();
Заменил let на const

2019-10-14 11:18 UTC, SerGeKon commented on index.js
> +    if (!(typeof (number) === 'number' && number >= 0)) {
Интересно почему number может быть 0, "...Второй - любое целое положительное число..."

2019-10-15 06:46 UTC, ghost requested changes

2019-10-15 06:46 UTC, AlexNg9 commented on index.js
> +    let result = 0;
Переменную лучше объявлять ближе к месту использования.

2019-10-15 06:46 UTC, AlexNg9 commented on index.js
> +    for (let i = 0; i < array.length; i++) {
Попробуйте разбить на два цикла. В одном – валидация массива, в другом получение числа. Используйте методы массива.

2019-10-15 06:46 UTC, AlexNg9 commented on index.js
> +    for (let i = 0; i < resultString.length; i++) {
Посмотрите, как можно одним методом разбить строку на массив символов/подстрок. Можно будет использовать map тогда.

2019-10-15 06:48 UTC, AlexNg9 commented on index.js
> +    if (!(typeof (number) === 'number' && number >= 0)) {
👍 
Ошибка в условии. Должно быть "неотрицательное число". Либо тест убрать лишний.

2019-10-15 09:43 UTC, SerGeKon commented on index.js
> +    let result = 0;
Понял.

2019-10-15 09:45 UTC, SerGeKon commented on index.js
> +    for (let i = 0; i < array.length; i++) {
Хм. Мне показалось сделать в одном цикле разумнее чем в 2.

2019-10-15 09:49 UTC, SerGeKon commented on index.js
> +    for (let i = 0; i < resultString.length; i++) {
Я думал обойтись без map, но видимо всё-таки придётся. :D

2019-10-15 10:13 UTC, AlexNg9 commented on index.js
> +    for (let i = 0; i < array.length; i++) {
С точки зрения оптимизации отчасти да. 
Сложность одного цикла – O(n). Двух – O(2n), то есть та же линия на самом деле O(n).
Поэтому на производительность это не повлияет. Зато становится лучше читаемость – декомпозируем логику. Отдельно валидация, отдельно получение результата.
Здесь маленький пример, поэтому не критично но самом деле, но хочется, чтобы вы это отработали все равно.

2019-10-15 10:13 UTC, AlexNg9 commented on index.js
> +    for (let i = 0; i < resultString.length; i++) {
Аналогично хочется, чтобы вы отработали + посмотрели на разные методы решения задачи сразу.

2019-10-15 10:15 UTC, SerGeKon commented on index.js
> +    for (let i = 0; i < array.length; i++) {
Понял. Спасибо за доходчивое объяснение.

2019-10-15 10:36 UTC, AlexNg9 commented on index.js
> +    for (let i = 0; i < array.length; i++) {
Обращайтесь. 👍

2019-10-15 10:54 UTC, SerGeKon commented on index.js
> +    }
Стоит ли объединять это условие с первым (проверяющим number)?

2019-10-15 11:01 UTC, SerGeKon commented on index.js
> +    if (!array.every((elem) => typeof (elem) === 'number' && elem >= 0 && elem <= 9)) {
Не совсем понимаю, почему здесь нужны скобки.

2019-10-15 11:42 UTC, AlexNg9 commented on index.js
> +    }
Можно собрать в одну проверку. Только в разные переменные их выделить.

2019-10-15 11:42 UTC, AlexNg9 commented on index.js
> +    if (!array.every((elem) => typeof (elem) === 'number' && elem >= 0 && elem <= 9)) {
Да вроде как не нужны как раз, можно без них.

2019-10-15 11:48 UTC, SerGeKon commented on index.js
> +    if (!array.every((elem) => typeof (elem) === 'number' && elem >= 0 && elem <= 9)) {
Ну, я сделал без них, но Azure попросила их.

2019-10-15 11:53 UTC, AlexNg9 commented on index.js
> +    if (!array.every((elem) => typeof (elem) === 'number' && elem >= 0 && elem <= 9)) {
Надо еще исправить линтер. :(

2019-10-15 11:54 UTC, AlexNg9 commented
👍

2019-10-15 11:54 UTC, closed without merging