zadanie1
frontend-tinkoff-ekb/rtf-lab-1 pull request #86
Opened 2019-10-14 12:13 UTC by pvpilizassal

2019-10-15 10:54 UTC, ghost requested changes

2019-10-15 10:54 UTC, AlexNg9 commented on index.js
> +        if (typeof array[i] === 'number' && array[i] <= 9 && array[i] >= 0) {
Реализуйте валидацию через метод массива.

2019-10-15 10:54 UTC, AlexNg9 commented on index.js
> +            sum = sum * 10 + array[i];
Получение результата тоже через метод можно.

2019-10-15 10:54 UTC, AlexNg9 commented on index.js
> +    const sum1 = [];
Плохое название.

2019-10-15 10:54 UTC, AlexNg9 commented on index.js
> +    const len = sum.toString().length;
Лучше хотя бы length. А еще лучше уточнить, длина какого объекта.

2019-10-15 10:54 UTC, AlexNg9 commented on index.js
> +    return (sum1);
Лишние скобки.

2019-10-15 10:54 UTC, AlexNg9 commented on index.js
> +    for (i = 0; i < array.length; i++) {
Можно в этой строке сразу let i.

2019-10-18 11:36 UTC, pvpilizassal commented on index.js
> +        if (typeof array[i] === 'number' && array[i] <= 9 && array[i] >= 0) {
Я вот уже несколько дней понять и нагуглить не могу, что вы имеете в виду

2019-10-18 11:36 UTC, pvpilizassal commented on index.js
> +            sum = sum * 10 + array[i];
И это тоже, может я настолько глупая, но не доходит просто

2019-10-18 11:57 UTC, pvpilizassal commented on index.js
> +        if (typeof array[i] === 'number' && array[i] <= 9 && array[i] >= 0) {
Я каждый день заходила, перечитывала и все равно не понимала, что это значит, даже гугл и учебник мне не помогли. Это провал :)

2019-10-18 12:33 UTC, AlexNg9 commented on index.js
> +        if (typeof array[i] === 'number' && array[i] <= 9 && array[i] >= 0) {
Посмотрите на методы массива every, some.

2019-10-18 12:33 UTC, AlexNg9 commented on index.js
> +            sum = sum * 10 + array[i];
Прочитайте про метод reduce.

2019-10-18 14:38 UTC, pvpilizassal commented on index.js
> +        if (typeof array[i] === 'number' && array[i] <= 9 && array[i] >= 0) {
На сколько я поняла, array.every(someFunction) вызывает функцию someFunction для каждого элемента массива, так это надо будет писать функцию someFunction, которая будет поочередно проверять элементы массива, внутри функции. Это разве проще?

2019-10-18 14:48 UTC, pvpilizassal commented on index.js
> +            sum = sum * 10 + array[i];
Про reduce все стало понятно, спасибо!

2019-10-19 11:36 UTC, AlexNg9 commented on index.js
> +        if (typeof array[i] === 'number' && array[i] <= 9 && array[i] >= 0) {
Этот метод специально для такой логики и придуман. Функцию необязательно отдельно объявлять в явном виде. Она может быть стрелочной, тогда кода будет меньше, чем в текущей записи.

2019-10-19 19:07 UTC, pvpilizassal commented on index.js
> +        if (typeof array[i] === 'number' && array[i] <= 9 && array[i] >= 0) {
Стрелочная ни в какую не получалась, но функцию реализовать получилось.

2019-10-20 14:59 UTC, ghost approved these changes
pvp ⚔️

2019-10-20 14:59 UTC, AlexNg9 commented on index.js
> +    if (array.every(checkNumber)) {
Необязательно было делать отдельную функцию. Можно было стрелочной.

2019-10-20 14:59 UTC, AlexNg9 commented on index.js
> +    if (array.every(checkNumber)) {
Лучше сделать:
`if (!array.every(...)) { return null }`

А дальше уже reduce сразу в переменную. И ее там же объявить.

2019-10-20 14:59 UTC, AlexNg9 commented on index.js
> +    const sumOfNumbers = [];
Не совсем корректно звучит название.

2019-10-20 14:59 UTC, AlexNg9 commented on index.js
> +    const lengthOfNumberFromArray = numberFromArray.toString().length;
Можно было не делать отдельную переменную.

2019-10-20 14:59 UTC, AlexNg9 commented on index.js
> +    const sumOfNumbers = [];
И сумма – число. А присваиваем массив.

2019-10-20 14:59 UTC, closed without merging

2019-10-20 15:00 UTC, AlexNg9 commented on index.js
> +        if (typeof array[i] === 'number' && array[i] <= 9 && array[i] >= 0) {
В чем проблема?