task1
frontend-tinkoff-ekb/rtf-lab-1 pull request #88
Opened 2019-10-14 13:00 UTC by slavker99

2019-10-15 10:55 UTC, AlexNg9 commented
@slavker99 
Зачем пр открывали-закрывали так много раз?

2019-10-15 10:58 UTC, ghost requested changes

2019-10-15 10:58 UTC, AlexNg9 commented on index.js
> +    let f = false;
Плохое название переменной.

2019-10-15 10:58 UTC, AlexNg9 commented on index.js
> +        if ((typeof array[i]) !== 'number') {
Нет смысла продолжать цикл, если это условие сработало. Можно сразу вернуть null. И в идеале это условие должно быть перед суммированием.

2019-10-15 10:58 UTC, AlexNg9 commented on index.js
> +    let str = '';
Аналогично. Что содержит строка?

2019-10-15 10:58 UTC, AlexNg9 commented on index.js
> +    let retArr = num.split('', array.length + number);
Что значит ret?

2019-10-15 10:58 UTC, AlexNg9 commented on index.js
> +    let retArr = num.split('', array.length + number);
Зачем второй аргумент?

2019-10-15 10:58 UTC, AlexNg9 commented on index.js
> +    if (f) {
От флага надо избавиться вообще.

2019-10-17 16:09 UTC, slavker99 commented
много раз переоткрывал пр потому что думал, что тесты не сработают, пока его не переоткроешь, извините) остальное всё исправил

2019-10-18 06:47 UTC, ghost requested changes

2019-10-18 06:47 UTC, AlexNg9 commented on index.js
> +    const returnedArray = num.split('', array.length + number);
Зачем в сплит второй аргумент? Название переменной плохое.

2019-10-18 06:47 UTC, AlexNg9 commented on index.js
> +    for (let i = 0; i < returnedArray.length; i++) {
Посмотрите на метод map.

2019-10-18 06:47 UTC, AlexNg9 commented on index.js
> +        if (((typeof array[i]) !== 'number') || ((array[i] < 0) || (array[i] > 9))) {
Вынесите проверку в отдельный цикл через some/every.

2019-10-21 06:34 UTC, ghost approved these changes
👍

2019-10-21 06:34 UTC, AlexNg9 commented on index.js
> +    const even = function (element) {
even – четный, в чем смысл?

2019-10-21 06:34 UTC, AlexNg9 commented on index.js
> +    let numFromArray = '';
Лучше ближе к месту использования объявить.

2019-10-21 06:34 UTC, AlexNg9 commented on index.js
> +    const convert = function (elem) {
Зачем в отдельную функцию? Почему не стрелочной?

2019-10-21 06:34 UTC, closed without merging